inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Disable annoying strict rules
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Style/StringLiterals:
  Enabled: false
